# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Papers',
            new_name='Paper',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
