# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20160827_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='page',
            name='cid',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
