# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_auto_20160827_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='cid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference'),
            preserve_default=False,
        ),
    ]
