# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_paper_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='description',
            field=models.CharField(default='Sample description', max_length=100),
            preserve_default=False,
        ),
    ]
