# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_conference_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='date',
        ),
        migrations.AddField(
            model_name='conference',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2016, 8, 27, 17, 27, 55, 795746, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2016, 8, 27, 17, 28, 5, 835024, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
