# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_auto_20160827_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pageUrl',
            field=models.CharField(default='home', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='pageName',
            field=models.CharField(max_length=50),
        ),
    ]
