# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 12:33
from __future__ import unicode_literals

import conferences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0016_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paperFile',
            field=models.FileField(upload_to=conferences.models.conference_directory_path, validators=[conferences.models.Paper.validate]),
        ),
    ]
