# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-24 09:49
from __future__ import unicode_literals

import conference.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=200)),
                ('branch_alias', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conf_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to=conference.models.get_conf_image_path)),
                ('imgname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conf_Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('paperRefNum', models.CharField(blank=True, max_length=15)),
                ('papername', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=100)),
                ('themes', models.CharField(blank=True, max_length=1000)),
                ('submissionDate', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('under_review', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('revisionNumber', models.IntegerField(default=1)),
                ('paperfile', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/media/rishu/Local Disk2/WSDC/CMS/CMSNITW/protected/'), upload_to=conference.models.get_conf_paper_path, validators=[conference.models.validate])),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('conference_name', models.CharField(max_length=100)),
                ('conference_alias', models.CharField(blank=True, max_length=50, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=10)),
                ('fee', models.IntegerField(default=0)),
                ('max_papers', models.IntegerField(default=1)),
                ('paperCount', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Branch')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('zipfile', models.FileField(blank=True, null=True, upload_to=conference.models.get_zip_file_path)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Final_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.CharField(max_length=50)),
                ('copyright_form', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/media/rishu/Local Disk2/WSDC/CMS/CMSNITW/protected/'), upload_to=conference.models.get_final_paper_path, validators=[conference.models.validate])),
                ('final_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/media/rishu/Local Disk2/WSDC/CMS/CMSNITW/protected/'), upload_to=conference.models.get_final_paper_path, validators=[conference.models.validate])),
                ('related_paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conference.Conf_Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('remarkFile', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/media/rishu/Local Disk2/WSDC/CMS/CMSNITW/protected/'), upload_to=conference.models.get_remark_file_path, validators=[conference.models.validate])),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('conf_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark', to='conference.Conf_Paper')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conf_paper',
            name='conf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
        migrations.AddField(
            model_name='conf_paper',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conf_image',
            name='conf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
    ]
