# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 15:08
from __future__ import unicode_literals

import conference.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to=conference.models.get_conf_image_path)),
                ('imgname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conf_Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('papername', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('submissionDate', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('paperfile', models.FileField(blank=True, null=True, upload_to=conference.models.get_conf_paper_path, validators=[conference.models.validate])),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('conference_name', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=10)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conf_paper',
            name='conf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
        migrations.AddField(
            model_name='conf_paper',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conf_image',
            name='conf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
    ]
