# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
