# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-09 19:20
from __future__ import unicode_literals

import conference.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=conference.models.get_image_path)),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='national',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
    ]
