# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_conference_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf_paper',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
