# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_conference_conference_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='max_papers',
            field=models.IntegerField(default=1),
        ),
    ]
