# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_conference_max_papers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conference_name',
            field=models.CharField(max_length=100),
        ),
    ]
