# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20161103_1311'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0007_conference_max_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('conf_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conf_Paper')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
