# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 14:43
from __future__ import unicode_literals

import conference.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_auto_20170105_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.CharField(max_length=50)),
                ('copyright_form', models.FileField(blank=True, null=True, upload_to=conference.models.get_final_paper_path, validators=[conference.models.validate])),
                ('final_file', models.FileField(blank=True, null=True, upload_to=conference.models.get_final_paper_path, validators=[conference.models.validate])),
            ],
        ),
        migrations.AlterField(
            model_name='conf_paper',
            name='papername',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='final_paper',
            name='related_paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conference.Conf_Paper'),
        ),
    ]
