# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_auto_20170105_1220'),
        ('conference', '0008_paper_remark'),
    ]

    operations = [
    ]
