# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_merge_20170105_2129'),
        ('conference', '0009_auto_20170106_1443'),
    ]

    operations = [
    ]
