# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_auto_20170123_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf_paper',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
