# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0015_paper_remark_remarkfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_remark',
            name='conf_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark', to='conference.Conf_Paper'),
        ),
    ]
