# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_auto_20170930_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf_paper',
            name='submissionDate',
            field=models.DateTimeField(),
        ),
    ]
