# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0017_auto_20170930_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf_paper',
            name='paperRefNum',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
