# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0018_conf_paper_paperrefnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='paperCount',
            field=models.IntegerField(default=0),
        ),
    ]
