# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-28 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0022_auto_20180828_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf_paper',
            name='papername',
            field=models.CharField(max_length=250),
        ),
    ]
