# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-28 08:33
from __future__ import unicode_literals

import conference.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0023_auto_20180828_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf_paper',
            name='paperfile',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/cms/ConferenceManagement/protected'), upload_to=conference.models.get_conf_paper_path, validators=[conference.models.validate]),
        ),
        migrations.AlterField(
            model_name='final_paper',
            name='copyright_form',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/cms/ConferenceManagement/protected'), upload_to=conference.models.get_final_paper_path, validators=[conference.models.validate]),
        ),
        migrations.AlterField(
            model_name='final_paper',
            name='final_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/cms/ConferenceManagement/protected'), upload_to=conference.models.get_final_paper_path, validators=[conference.models.validate]),
        ),
        migrations.AlterField(
            model_name='paper_remark',
            name='remarkFile',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/cms/ConferenceManagement/protected'), upload_to=conference.models.get_remark_file_path, validators=[conference.models.validate]),
        ),
    ]
