# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-26 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0028_auto_20181012_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf_paper',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper', to=settings.AUTH_USER_MODEL),
        ),
    ]
