# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-26 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0029_auto_20181026_1429'),
        ('conference', '0029_auto_20181014_0613'),
    ]

    operations = [
    ]
