# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20161024_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='reviewer',
        ),
    ]
