# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_questions_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.Reviewer'),
        ),
    ]
