# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_conference_fee'),
        ('reviews', '0005_auto_20161028_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='paper',
        ),
        migrations.AddField(
            model_name='questions',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
    ]
