# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_conference_fee'),
        ('reviews', '0006_auto_20161102_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Conf_Paper'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
    ]
