# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_auto_20161103_1311'),
        ('reviews', '0008_auto_20161103_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(default='Remarks', max_length=100)),
                ('answer', models.TextField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conf_Paper')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Reviewer')),
            ],
        ),
    ]
