# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarks',
            name='remark',
        ),
    ]
