# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-08 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_remove_remarks_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
