# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-08 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0019_conference_papercount'),
        ('reviews', '0011_answers_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPaperStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewStatus', models.IntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conf_Paper')),
            ],
        ),
    ]
