# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_assignedpaperstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedpaperstatus',
            name='reviewer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reviews.Reviewer'),
            preserve_default=False,
        ),
    ]
