# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-28 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0019_conference_papercount'),
        ('reviews', '0013_assignedpaperstatus_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='ans_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
    ]
