# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20180328_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='ans_type',
        ),
        migrations.AddField(
            model_name='questions',
            name='que_type',
            field=models.IntegerField(default=0),
        ),
    ]
