# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-24 09:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import login_auth.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0001_initial'),
        ('login_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseName', models.CharField(max_length=255)),
                ('tariff', models.IntegerField()),
                ('house_id', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'female')], max_length=15)),
                ('seatsAvailable', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AccomodationPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_receipt', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/media/rishu/Local Disk2/WSDC/CMS/CMSNITW/protected/'), upload_to=login_auth.models.get_acc_path)),
                ('numer_of_rooms', models.IntegerField(default=1)),
                ('is_aprooved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('review', models.CharField(default='', max_length=500)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('conf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
                ('house_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_auth.Accomodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
