# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0001_initial'),
        ('login_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
                ('papers', models.ManyToManyField(blank=True, null=True, to='conference.Conf_Paper')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='regConferences',
            field=models.ManyToManyField(blank=True, null=True, to='login_auth.Registered_Conference'),
        ),
    ]
