# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-24 05:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodationpayment',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='accomodationpayment',
            name='review',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='accomodationpayment',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
