# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0002_accomodation_accomodationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='seatsAvailable',
            field=models.IntegerField(default=0),
        ),
    ]
