# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 10:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login_auth.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0002_conference_fee'),
        ('login_auth', '0002_auto_20161013_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('payment_mode', models.CharField(choices=[('net', 'Net Banking'), ('dd', 'Through DD')], max_length=20)),
                ('pic_of_dd', models.ImageField(blank=True, null=True, upload_to=login_auth.models.get_dd_path)),
                ('is_aprooved', models.BooleanField(default=False)),
                ('conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
