# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-25 06:01
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import login_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
        ('login_auth', '0002_auto_20190125_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomodationPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=255)),
                ('paper_id', models.CharField(blank=True, default=None, max_length=255)),
                ('reference_number', models.CharField(default=None, max_length=255)),
                ('payment_receipt', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/cms/ConferenceManagement/protected/'), upload_to=login_auth.models.get_acc_path)),
                ('email', models.CharField(default='', max_length=255)),
                ('is_aprooved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('review', models.CharField(default='', max_length=500)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('conf_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
                ('house_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_auth.Accomodation')),
            ],
        ),
    ]
