# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-13 13:37
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import login_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0003_accomodation_seatsavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodationpayment',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/mnt/e/code/wsdc/cms/CMSNITW/protected/'), upload_to=login_auth.models.get_acc_path),
        ),
    ]
