# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0004_auto_20161028_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
