# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0005_payment_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
