# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-24 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0005_auto_20190122_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodationpayment',
            name='numer_of_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accomodationpayment',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 24, 13, 50, 56, 501627)),
        ),
        migrations.AlterField(
            model_name='accomodationpayment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 24, 13, 50, 56, 501553)),
        ),
    ]
