# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0006_auto_20161028_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
