# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login_auth.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0004_auto_20161103_1311'),
        ('login_auth', '0007_payment_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejected_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_of_dd', models.ImageField(blank=True, null=True, upload_to=login_auth.models.get_dd_path)),
                ('date', models.DateField()),
                ('conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
