# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import login_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0008_rejected_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pic_of_id',
            field=models.ImageField(blank=True, null=True, upload_to=login_auth.models.get_dd_path),
        ),
    ]
