# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0009_payment_pic_of_id'),
        ('login_auth', '0009_auto_20170105_1146'),
    ]

    operations = [
    ]
