# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0010_merge_20170107_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='institute',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
