# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0011_userprofile_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rejected_payment',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
