# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-28 03:44
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import login_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0016_auto_20180624_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pic_of_dd',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/tauhid/Desktop/WSDC/CMS/ConferenceManagement/protected'), upload_to=login_auth.models.get_dd_path),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pic_of_id',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/tauhid/Desktop/WSDC/CMS/ConferenceManagement/protected'), upload_to=login_auth.models.get_dd_path),
        ),
        migrations.AlterField(
            model_name='registered_conference',
            name='papers',
            field=models.ManyToManyField(blank=True, to='conference.Conf_Paper'),
        ),
        migrations.AlterField(
            model_name='rejected_payment',
            name='pic_of_dd',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/tauhid/Desktop/WSDC/CMS/ConferenceManagement/protected'), upload_to=login_auth.models.get_dd_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='regConferences',
            field=models.ManyToManyField(blank=True, to='login_auth.Registered_Conference'),
        ),
    ]
