# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-08 05:26
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import login_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0018_auto_20180828_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=255)),
                ('branch', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pic_of_dd',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/tauhid/Desktop/WSDC/CMS/ConferenceManagement/protected'), upload_to=login_auth.models.get_dd_path),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pic_of_id',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/tauhid/Desktop/WSDC/CMS/ConferenceManagement/protected'), upload_to=login_auth.models.get_dd_path),
        ),
        migrations.AlterField(
            model_name='rejected_payment',
            name='pic_of_dd',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/tauhid/Desktop/WSDC/CMS/ConferenceManagement/protected'), upload_to=login_auth.models.get_dd_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alumani',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_auth.Alumani'),
        ),
    ]
