# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-08 11:24
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import login_auth.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_auth', '0019_auto_20180908_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('delegate', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=255)),
                ('orgType', models.CharField(max_length=255, null=True)),
                ('md_cco', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=255)),
                ('advertisement', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/tauhid/Desktop/WSDC/CMS/ConferenceManagement/protected'), upload_to=login_auth.models.get_adv_path, validators=[login_auth.models.validate])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='delegates',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_auth.SponsorProfile'),
        ),
    ]
