# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-08 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0025_auto_20180908_1056'),
        ('login_auth', '0020_auto_20180908_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='conf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
    ]
