# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-11 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import login_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0021_sponsorprofile_conf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='is_aprooved',
            new_name='is_aproved',
        ),
        migrations.AlterField(
            model_name='sponsorprofile',
            name='advertisement',
            field=models.FileField(blank=True, null=True, upload_to=login_auth.models.get_adv_path, validators=[login_auth.models.validate]),
        ),
    ]
