# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0024_auto_20180926_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
