# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-26 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0025_userprofile_mail_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mail_sent',
            new_name='mail_sent_accept',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mail_sent_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mail_sent_reject',
            field=models.BooleanField(default=False),
        ),
    ]
