# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-04 08:54
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import login_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0026_auto_20180927_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refno',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='rejected_payment',
            name='refno',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pic_of_dd',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/cms/ConferenceManagement/protected/'), upload_to=login_auth.models.get_dd_path),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pic_of_id',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/cms/ConferenceManagement/protected/'), upload_to=login_auth.models.get_dd_path),
        ),
        migrations.AlterField(
            model_name='rejected_payment',
            name='pic_of_dd',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/cms/ConferenceManagement/protected/'), upload_to=login_auth.models.get_dd_path),
        ),
    ]
