# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_assign',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='paper_assign',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='paper_assign',
            name='reviewers',
        ),
        migrations.DeleteModel(
            name='Paper_assign',
        ),
    ]
